version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: npm install discord.js
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run start
workflows:
  test_my_app:
    jobs:
      - test
