version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: npm install discord.js
workflows:
  test_my_app:
    jobs:
      - install-node-example
    

