version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  no_output_timeout: 24h
  run:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install discord.js
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run deploy
      - run: npm run start

     
workflows:
  Log:
    jobs:
      - run